package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

import bean.UserBean;

public class UserDAO {
	DataSource ds;
	
	public UserDAO() throws ClassNotFoundException {

		try {
			ds = (DataSource) (new InitialContext()).lookup("java:/comp/env/jdbc/EECS");
		} catch (NamingException e) {
			e.printStackTrace();
		}
	}
	
	public UserBean addNewUser(String email, String password, String fname, 
				String lname, String street, String province, String country, String zip, String phone){
		UserBean user = null;
		try{
			Connection con = this.ds.getConnection();
			Statement st = con.createStatement();
			
			// Insert a new user into the Users table
			String updateUser = "INSERT INTO Users (fname, lname, email, password) VALUES ('" 
					+ fname + "', '" + lname + "', '" + email + "', '" + password + "')";
			st.executeUpdate(updateUser);
			
			// After adding the user retrieve the uid generated by the database
			String query = "select uid from Users where fname = '" 
					+ fname + "' and lname = '" + lname + "' and email = '" + email + "' and password = '" + password + "'";
			PreparedStatement p2 = con.prepareStatement(query);

			ResultSet r = p2.executeQuery();
			r.next();
			
			int uid = r.getInt("uid");
			
			user = new UserBean(uid, fname, lname, email, password);
			
			p2.close();
			r.close();
			
			// Add the address to the database connected to the uid 
			String updateAdd = "INSERT INTO Address (uid, street, province, country, zip, phone) VALUES (" 
					+ uid + ", '" + street + "', '" + province + "', '" + country + "', '" + zip + "' ,'" + phone + "')";
			st.executeUpdate(updateAdd);
			st.close();
			con.close();
			
		}catch (Exception e){
			e.printStackTrace();
		}
		return user;
	}
	
}
